[package]
name = "estar-sale-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.estar-sale]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.35.0"
